import asyncio
import logging
import google.generativeai as genai
from backend.config import settings
from backend.app.models import ScraperOutput
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

# Configure the Gemini API
try:
    genai.configure(api_key=settings.GEMINI_API_KEY)
    # Use gemini-flash-latest for stability and quota
    model = genai.GenerativeModel(
        model_name='gemini-flash-latest',
        generation_config={
            "temperature": 0.7,
            "top_p": 0.95,
            "top_k": 64,
            "max_output_tokens": 8192,
        },
        safety_settings=[
            {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE"},
            {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE"},
            {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_NONE"},
            {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_NONE"},
        ]
    )
except Exception as e:
    logger.error(f"Failed to configure Gemini API: {e}")
    model = None

def get_system_context():
    return (
        "You are a senior trade analyst at an Indian commerce think tank. "
        "You specialize in identifying trade opportunities for Indian businesses. "
        "Always cite specific numbers, percentages, and company names when available. "
        "Be specific, data-driven, and actionable."
    )

def create_prompt(scraper_data: ScraperOutput) -> str:
    sector = scraper_data['sector']
    # Limit raw text to avoid hitting context limits, though Flash is large
    raw_text = scraper_data['raw_text_combined'][:30000] 
    source_count = scraper_data['total_sources']
    news_items = "\n".join([
        f"- {item['title']}" for item in scraper_data['sources'].get('news', [])
    ])
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    
    urls = []
    if isinstance(scraper_data['sources'].get('duckduckgo'), list):
        urls.extend([item['url'] for item in scraper_data['sources']['duckduckgo'] if item.get('url')])
    if isinstance(scraper_data['sources'].get('news'), list):
        urls.extend([item['url'] for item in scraper_data['sources']['news'] if item.get('url')])

    return f"""    
    Analyze the following live market data collected about the {sector} sector in India 
    and generate a comprehensive trade opportunities report.
    
    === LIVE MARKET DATA ===
    {raw_text}
    
    === NEWS HEADLINES (last 7 days) ===
    {news_items}
    
    === GENERATE THIS EXACT MARKDOWN STRUCTURE ===
    DO NOT include any conversational filler. Start directly with the # heading.
    
    # 🏭 Trade Opportunities Report: {sector.title()} Sector — India
    **Generated:** {timestamp} | **Data Sources:** {source_count} | **Analysis by:** Gemini AI
    
    ---
    
    ## 📊 Executive Summary
    [Provide a 3-4 sentence summary with key numbers and current market status]
    
    ## 🌍 Current Market Landscape
    ### Market Size & Growth
    [Detailed stats, CAGR, projections]
    ### Recent Developments
    [Summary of last 3-6 months news and changes]
    
    ## 💰 Top Trade Opportunities
    ### Opportunity 1: [Name]
    - **Type:** Export/Import/Domestic
    - **Potential Value:** ₹X Crore / $X Million
    - **Timeline:** Short/Medium/Long term
    - **Why Now:** [Detailed reasoning]
    
    [Provide at least 3 opportunities]
    
    ## 📦 Export Opportunities
    ### Top Export Products
    ### Target Markets (countries)
    ### Projected Growth
    
    ## 🛒 Import Opportunities
    ### Supply Gaps
    ### Sourcing Recommendations
    
    ## 🏢 Key Players
    ### Top Indian Companies
    ### Government Bodies & Regulators
    ### Industry Associations
    
    ## 📜 Policy & Regulatory Environment
    ### Favorable Policies
    ### FTAs & Trade Agreements
    ### Incentives & Subsidies
    
    ## ⚠️ Risk Factors
    | Risk | Impact | Mitigation |
    |------|--------|------------|
    | [Risk Name] | [High/Medium/Low] | [Mitigation Strategy] |
    
    ## ✅ Actionable Recommendations
    1. [Specific action for importers]
    2. [Specific action for exporters]
    3. [Specific action for investors]
    4. [Policy/compliance action]
    5. [Market entry strategy]
    
    ## 📚 Data Sources
    {chr(10).join(f"- {url}" for url in urls[:10])}
    
    ---
    *Report generated by TradeIQ India | Data collected via live web scraping*
    """

async def generate_report(scraper_data: ScraperOutput) -> str:
    if not model:
        logger.error("Gemini model not initialized. Cannot generate report.")
        return create_fallback_report(scraper_data, "Model not initialized.")

    prompt = create_prompt(scraper_data)
    system_context = get_system_context()
    
    # Combined prompt for better context handling
    full_prompt = f"{system_context}\n\n{prompt}"

    try:
        # Using run_in_executor to run the synchronous SDK call in an async context
        loop = asyncio.get_running_loop()
        response = await loop.run_in_executor(
            None,  # uses the default executor (a ThreadPoolExecutor)
            lambda: model.generate_content(full_prompt)
        )
        
        if not response or not response.text:
            logger.error("Gemini API returned an empty response.")
            return create_fallback_report(scraper_data, "Empty response from AI.")
            
        logger.info(f"Gemini API call successful for sector: {scraper_data['sector']}")
        return response.text
    except Exception as e:
        error_msg = str(e)
        logger.error(f"Gemini API call failed: {error_msg}")
        
        # Check if it's a quota error
        if "Quota exceeded" in error_msg:
            return create_fallback_report(scraper_data, "Gemini API Quota Exceeded. Please try again in a few minutes.")
            
        # Log more details if it's a safety filter issue
        if hasattr(e, 'response') and hasattr(e.response, 'candidates'):
            logger.error(f"Safety filter or other issue details: {e.response.candidates}")
            return create_fallback_report(scraper_data, "Content blocked by AI safety filters.")
            
        return create_fallback_report(scraper_data, f"AI Analysis failed: {error_msg}")

def create_fallback_report(scraper_data: ScraperOutput, reason: str = "Unknown error") -> str:
    sector = scraper_data['sector']
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    
    # Pre-process news items to avoid redirects if possible (but we'll just display them)
    news_html = ""
    for item in scraper_data['sources'].get('news', []):
        news_html += f"- **{item['title']}** ({item['date']})\n  [Link]({item['url']})\n\n"

    return f"""# 🏭 Trade Data Summary: {sector.title()} Sector
**Generated:** {timestamp} | **Status:** ⚠️ AI Analysis Limited

---

## 🚨 Analysis Unavailable
**Reason:** {reason}

While the full AI-generated report could not be completed, here is the raw market data collected for your review.

---

## 📰 Recent News Headlines
{news_html or "No recent news found."}

## 📊 Raw Scraped Data
### DUCKDUCKGO
{scraper_data['sources'].get('duckduckgo', []) or "[]"}

### ECONOMIC_TIMES
{scraper_data['sources'].get('economic_times', []) or "[]"}

### WIKIPEDIA
{scraper_data['sources'].get('wikipedia', {}) or "{}"}

### GOV_DATA
{scraper_data['sources'].get('gov_data', []) or "[]"}

---
*Data collected via TradeIQ India scraper. Full analysis will be available once AI quota resets.*
"""
